# Generated by Django 4.2.8 on 2024-05-09 21:13

import apps.widget_settings.dto.settings
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_pydantic_field.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WidgetSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "settings",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        help_text="Настройки окна траснляции",
                        schema=apps.widget_settings.dto.settings.SettingsDto,
                        verbose_name="Настройки окна траснляции",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки виджета",
                "verbose_name_plural": "Настройки виджета",
            },
        ),
    ]
