# Generated by Django 4.2.8 on 2024-05-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("widget_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="widgetsettings",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Ключ настроек",
                max_length=255,
                null=True,
                verbose_name="Ключ настроек",
            ),
        ),
    ]
